### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by wjhtinger** [rticommunity/libsel4osapi#1]
No updates for a long time.

**Comment by fabriziobertocci** [comment]
This version has not been more developed. We have a newer version but that is based on some non-public userspace library. Another version of our Connext DDS Micro is built on top of TRENTOS-M (CAmkES-based) and does not require anymore a OSAPI compatibility layer library.
Can you provide more information about your project?

**Comment by wjhtinger** [comment]
> This version has not been more developed. We have a newer version but that is based on some non-public userspace library. Another version of our Connext DDS Micro is built on top of TRENTOS-M (CAmkES-based) and does not require anymore a OSAPI compatibility layer library. Can you provide more information about your project?

I just want to develop an security applicaiton system based on sel4, but find that the sel4 programing interface is not friendly verymuch. So, I want found some opensouce lib or framework on sel4 for easy programing. So, can you give some ideas? And your new version project is properties, right?

**Comment by fabriziobertocci** [comment]
The new version is useless because is based on the library from COE (Center of Excellence) that was created 3 years ago and didn't really took off, so, it's pointless to release the new version as it is only a thin wrapper around the COE primitive. And COE source code is not public (I believe is still accessible for some DoD-related projects).
In your case your best way to develop seL4-based application without getting lost in the libraries is to use [CAmkES](https://docs.sel4.systems/projects/camkes/).
It's not straight forward and you need to learn all the concepts behind CAmkES, but all the OS-wiring part (task creation, memory management, ...) is already done and there are many components available you can use out of the box.

**Comment by wjhtinger** [comment]
> The new version is useless because is based on the library from COE (Center of Excellence) that was created 3 years ago and didn't really took off, so, it's pointless to release the new version as it is only a thin wrapper around the COE primitive. And COE source code is not public (I believe is still accessible for some DoD-related projects). In your case your best way to develop seL4-based application without getting lost in the libraries is to use [CAmkES](https://docs.sel4.systems/projects/camkes/). It's not straight forward and you need to learn all the concepts behind CAmkES, but all the OS-wiring part (task creation, memory management, ...) is already done and there are many components available you can use out of the box.


Thank you very much. I take a look at CAmkES, find that architecture is still weird for a traditional programmer, need to learn a lot about context. So, I want to know if there are some framework on top of sel4, on which I can program legacy application, like in Linux system. I heard that Genode is a OS on top of sel4, so how about it? can it solve my problem?

**Comment by fabriziobertocci** [comment]
Genode is similar to CAmkES, it is a component based framework. The most important difference is that in CAmkES your system architecture is statically defined, while on Genode you can dynamically connect and disconnect components at run-time. Genode also supports different microkernels, not only seL4. 

Andrew W. is working on a full OS (similar to QNX) based on seL4, you can read more about his project here: https://gitlab.com/uxrt
... but I don't know how advanced/stable is the project.

TRENTOS-M is another very mature framework, it is based on CAmkES, but it is a commercial solution (from Hensoldt Cyber).

As I said, for what you describe, your best bet is to learn and use CAmkES.
